apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bizpark
resources:
  - ../../base
images:
  - name: ghcr.io/codesprint-bizspark/bizpark-api
    newName: ghcr.io/codesprint-bizspark/bizpark-api
    digest: sha256:d2ef973f4c391a608c1835f182b2ac248a8c0b9425ed9375088a2f1162fc64c8
  - name: ghcr.io/codesprint-bizspark/bizpark-admin
    newName: ghcr.io/codesprint-bizspark/bizpark-admin
    digest: sha256:0ccca5dade6d466305721c4ace2370e5d8aa352bef6df1bbf34d837afc5f7d77
  - name: ghcr.io/codesprint-bizspark/bizpark-commerce
    newName: ghcr.io/codesprint-bizspark/bizpark-commerce
    digest: sha256:2c19c8928de18719e525a30274d2e87465b4c3bb2eda836e420f0cf7bc0cc436
  - name: ghcr.io/codesprint-bizspark/bizpark-commerce-web
    newName: ghcr.io/codesprint-bizspark/bizpark-commerce-web
    digest: sha256:e7ebba812b8bcbbf83efe9618dda71cd419e2e26f71d3288a91f7bd224f5e8bc
  - name: ghcr.io/codesprint-bizspark/bizpark-runner
    newName: ghcr.io/codesprint-bizspark/bizpark-runner
    digest: sha256:ac48f922e9bb71489c5972d4bcd0c5c2824068fc070f0bd995f232e0256214fb
labels:
  - pairs:
      app.kubernetes.io/part-of: bizpark
    includeSelectors: true
