apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bizpark
resources:
  - ../../base
images:
  - name: ghcr.io/codesprint-bizspark/bizpark-api
    newName: ghcr.io/codesprint-bizspark/bizpark-api
    digest: sha256:c32a226e894214c6be40e8d321a112876701c06ef088f64ac879b34100923d01
  - name: ghcr.io/codesprint-bizspark/bizpark-admin
    newName: ghcr.io/codesprint-bizspark/bizpark-admin
    digest: sha256:f865443a133b0e6bc2f0f75d4eae4b7c693f633f59c36f20b8d8da6780642de0
  - name: ghcr.io/codesprint-bizspark/bizpark-commerce
    newName: ghcr.io/codesprint-bizspark/bizpark-commerce
    digest: sha256:7ea0b43ae7054929e558dc5dc15156373ad5652e21fb9dbd8f12ff60e4dcc3ae
  - name: ghcr.io/codesprint-bizspark/bizpark-commerce-web
    newName: ghcr.io/codesprint-bizspark/bizpark-commerce-web
    digest: sha256:a2dff1d3259eb47f2d4b9827e3cd53bec2886bc79f73bd248e903a8f57c8c5b1
  - name: ghcr.io/codesprint-bizspark/bizpark-runner
    newName: ghcr.io/codesprint-bizspark/bizpark-runner
    digest: sha256:15f5cc9c05fc3f85bf35cd55dfed961166ef357763481d7272455d092c87253e
  - name: ghcr.io/codesprint-bizspark/bizpark-mcp
    newName: ghcr.io/codesprint-bizspark/bizpark-mcp
    digest: sha256:8a2f10a121ec04ff289b8332b5d4a4c8236a4a861d318d122bc1daf767ff985b
labels:
  - pairs:
      app.kubernetes.io/part-of: bizpark
    includeSelectors: true
